extend-exclude = ["*_pb2.py", "*_pb2_grpc.py"]
line-length = 120
target-version = "py311"

[lint]
ignore = [
  "COM812", # conflicts with the formatter
  "D203",   # conflicts with D211 (one-blank-line-before-class vs no-blank-line-before-class)
  "D213",   # conflicts with D212 (multi-line-summary-second-line vs multi-line-summary-first-line)
]

# Tighten rules
select = ["ALL"]

[lint.per-file-ignores]
"**/*.py" = ["INP001"]
